import * as Clipboard from "expo-clipboard";
import { File, Paths } from "expo-file-system";
import * as Sharing from "expo-sharing";
import { useEffect, useState } from "react";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Alert, FlatList, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { haptic } from "@/lib/haptics";
import { useRebelSession } from "@/lib/rebel-session";
import { trpc } from "@/lib/trpc";

type ArtifactType = "document" | "plan" | "table" | "decision";
type Artifact = { id: number; type: ArtifactType; title: string; content: string };
const types: { value: ArtifactType; label: string; color: string }[] = [{ value: "document", label: "مستند", color: "#2563EB" }, { value: "plan", label: "خطة", color: "#16835D" }, { value: "table", label: "جدول", color: "#A16207" }, { value: "decision", label: "قرار", color: "#7C3AED" }];

export default function ArtifactsScreen() {
  const router = useRouter(); const { projectId: rawProjectId } = useLocalSearchParams<{ projectId?: string }>(); const projectId = Number(rawProjectId);
  const { session, loading } = useRebelSession(); const enabled = Boolean(session && Number.isInteger(projectId) && projectId > 0);
  const artifacts = trpc.cloud.artifacts.list.useQuery({ projectId }, { enabled });
  const createArtifact = trpc.cloud.artifacts.create.useMutation({ onSuccess: () => artifacts.refetch() }); const updateArtifact = trpc.cloud.artifacts.update.useMutation({ onSuccess: () => artifacts.refetch() }); const deleteArtifact = trpc.cloud.artifacts.delete.useMutation({ onSuccess: () => artifacts.refetch() });
  const [editingId, setEditingId] = useState<number | null>(null); const [type, setType] = useState<ArtifactType>("document"); const [title, setTitle] = useState(""); const [content, setContent] = useState("");
  const pending = createArtifact.isPending || updateArtifact.isPending;
  useEffect(() => { if (!loading && !session) router.replace("/login" as never); }, [loading, router, session]);
  const reset = () => { setEditingId(null); setType("document"); setTitle(""); setContent(""); };
  const save = async () => { if (!enabled || !title.trim() || !content.trim() || pending) return; try { if (editingId) await updateArtifact.mutateAsync({ artifactId: editingId, type, title: title.trim(), content: content.trim() }); else await createArtifact.mutateAsync({ projectId, type, title: title.trim(), content: content.trim() }); reset(); haptic.success(); } catch { Alert.alert("تعذر حفظ المخرج", "تحقق من اتصالك ثم أعد المحاولة."); haptic.warning(); } };
  const copy = async (value: string) => { try { await Clipboard.setStringAsync(value); haptic.success(); Alert.alert("تم النسخ", "يمكنك لصق المخرج في أي تطبيق."); } catch { Alert.alert("تعذر النسخ", "حاول مرة أخرى."); } };
  const share = async (item: Artifact) => { try { const value = `${item.title}\n\n${item.content}`; if (Platform.OS === "web") { await Clipboard.setStringAsync(value); Alert.alert("تم النسخ", "المشاركة من الويب غير مضمونة، لذلك نُسخ النص."); return; } const file = new File(Paths.cache, `rebel-${item.id}.txt`); file.create({ overwrite: true }); file.write(value); if (!(await Sharing.isAvailableAsync())) throw new Error("sharing unavailable"); await Sharing.shareAsync(file.uri, { mimeType: "text/plain", dialogTitle: "مشاركة مخرج من Rebel AI" }); haptic.success(); } catch { Alert.alert("تعذر فتح المشاركة", "جرّب النسخ بدلاً من ذلك."); } };
  if (loading || !session) return <ScreenContainer className="items-center justify-center px-6"><Text style={styles.gate}>{loading ? "جارٍ التحقق من الجلسة…" : "يتم تحويلك إلى تسجيل الدخول…"}</Text></ScreenContainer>;
  if (!enabled) return <ScreenContainer className="items-center justify-center px-6"><Text style={styles.gate}>اختر مشروعاً أولاً لفتح المخرجات.</Text></ScreenContainer>;
  const renderItem = ({ item }: { item: Artifact }) => { const entry = types.find((value) => value.value === item.type)!; return <View style={styles.card}><View style={styles.cardTop}><View style={[styles.badge, { backgroundColor: `${entry.color}14` }]}><Text style={[styles.badgeText, { color: entry.color }]}>{entry.label}</Text></View><Text style={styles.cardTitle}>{item.title}</Text></View><Text style={styles.cardContent} numberOfLines={6}>{item.content}</Text><View style={styles.actions}><Pressable onPress={() => { setEditingId(item.id); setType(item.type); setTitle(item.title); setContent(item.content); }}><Text style={styles.edit}>تعديل</Text></Pressable><Pressable onPress={() => copy(`${item.title}\n\n${item.content}`)}><Text style={styles.copy}>نسخ</Text></Pressable><Pressable onPress={() => share(item)}><Text style={styles.copy}>مشاركة</Text></Pressable><Pressable onPress={() => Alert.alert("حذف المخرج؟", "لن يمكن استعادته من المشروع.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => deleteArtifact.mutate({ artifactId: item.id }) }])}><Text style={styles.delete}>حذف</Text></Pressable></View></View>; };
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.page}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.right" size={23} color="#202026" /></Pressable><View><Text style={styles.title}>مخرجات المشروع</Text><Text style={styles.subtitle}>حوّل الأفكار إلى مستندات وخطط وجداول وقرارات قابلة للتحرير</Text></View><View style={styles.spacer} /></View><FlatList data={(artifacts.data ?? []) as Artifact[]} renderItem={renderItem} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.form}><Text style={styles.formTitle}>{editingId ? "تعديل المخرج" : "مخرج جديد"}</Text><View style={styles.typeRow}>{types.map((entry) => <Pressable key={entry.value} onPress={() => setType(entry.value)} style={[styles.type, type === entry.value && { backgroundColor: entry.color, borderColor: entry.color }]}><Text style={[styles.typeText, type === entry.value && styles.typeTextActive]}>{entry.label}</Text></Pressable>)}</View><TextInput value={title} onChangeText={setTitle} placeholder="عنوان المخرج" placeholderTextColor="#94949C" style={styles.input} textAlign="right" /><TextInput value={content} onChangeText={setContent} placeholder="اكتب المحتوى أو الصق رد Rebel ثم عدّله" placeholderTextColor="#94949C" style={[styles.input, styles.contentInput]} textAlign="right" multiline /><View style={styles.formActions}><Pressable onPress={save} disabled={!title.trim() || !content.trim() || pending} style={[styles.save, (!title.trim() || !content.trim() || pending) && styles.disabled]}><Text style={styles.saveText}>{pending ? "جارٍ الحفظ…" : editingId ? "حفظ التعديل" : "إضافة للمشروع"}</Text></Pressable>{editingId ? <Pressable onPress={reset} style={styles.cancel}><Text style={styles.cancelText}>إلغاء</Text></Pressable> : null}</View></View>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>لا توجد مخرجات بعد</Text><Text style={styles.emptyText}>أنشئ مستنداً أو خطة أو جدولاً لتحويل المحادثة إلى عمل يمكن تعديله ومشاركته.</Text></View>} /></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 8 }, gate: { color: "#73737C", fontSize: 14, textAlign: "center" }, header: { minHeight: 62, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }, back: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#E8E8EB" }, title: { color: "#17171A", fontSize: 22, fontWeight: "900", textAlign: "center" }, subtitle: { color: "#777780", fontSize: 10, textAlign: "center", marginTop: 3 }, spacer: { width: 44 }, list: { gap: 10, paddingBottom: 28 }, form: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E5EA", borderRadius: 18, padding: 14, gap: 10, marginBottom: 14 }, formTitle: { color: "#28282E", fontSize: 16, fontWeight: "900", textAlign: "right" }, typeRow: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, type: { borderWidth: 1, borderColor: "#DFE1E6", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8, backgroundColor: "#FAFAFB" }, typeText: { color: "#62626B", fontSize: 11, fontWeight: "800" }, typeTextActive: { color: "#FFFFFF" }, input: { minHeight: 44, color: "#28282E", fontSize: 13, borderWidth: 1, borderColor: "#E3E3E7", borderRadius: 11, paddingHorizontal: 11, backgroundColor: "#FBFBFC" }, contentInput: { minHeight: 110, paddingTop: 10, lineHeight: 19 }, formActions: { flexDirection: "row-reverse", gap: 9 }, save: { flex: 1, borderRadius: 11, paddingVertical: 12, alignItems: "center", backgroundColor: "#2563EB" }, saveText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, cancel: { borderRadius: 11, paddingHorizontal: 16, justifyContent: "center", backgroundColor: "#F0F0F3" }, cancelText: { color: "#5E5E66", fontWeight: "800", fontSize: 12 }, disabled: { opacity: 0.45 }, card: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E7E7EA", borderRadius: 17, padding: 14, gap: 9 }, cardTop: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", gap: 10 }, badge: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9 }, badgeText: { fontSize: 10, fontWeight: "900" }, cardTitle: { flex: 1, color: "#26262C", fontSize: 15, fontWeight: "900", textAlign: "right" }, cardContent: { color: "#62626C", fontSize: 12, lineHeight: 19, textAlign: "right" }, actions: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 14 }, edit: { color: "#2563EB", fontSize: 11, fontWeight: "900" }, copy: { color: "#16835D", fontSize: 11, fontWeight: "900" }, delete: { color: "#B34A5C", fontSize: 11, fontWeight: "900" }, empty: { backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E7E7EA", alignItems: "center", padding: 28, gap: 8 }, emptyTitle: { color: "#34343A", fontWeight: "900", fontSize: 15 }, emptyText: { color: "#777780", lineHeight: 19, textAlign: "center", fontSize: 12 } });
