import { useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenHeading, StatusPill } from "@/components/rebel-ui";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { trpc } from "@/lib/trpc";

const providers = [{ id: "gemini", name: "Gemini Flash", note: "من Google AI Studio" }, { id: "groq", name: "Qwen عبر Groq", note: "من Groq Console" }, { id: "mistral", name: "Mistral Small", note: "من Mistral AI" }] as const;
type ProviderId = (typeof providers)[number]["id"];

export default function KeysScreen() {
  const router = useRouter();
  const [provider, setProvider] = useState<ProviderId>("gemini");
  const [apiKey, setApiKey] = useState("");
  const statuses = trpc.account.providerKeyStatuses.useQuery();
  const save = trpc.account.testAndSaveProviderKey.useMutation({ onSuccess: () => { setApiKey(""); statuses.refetch(); haptic.success(); Alert.alert("تم الحفظ", "اختبر Rebel AI المفتاح بنجاح وحفظه مشفراً على الخادم."); } });
  const remove = trpc.account.deleteProviderKey.useMutation({ onSuccess: () => { statuses.refetch(); haptic.medium(); } });
  const saved = useMemo(() => new Set(statuses.data?.map((item) => item.provider) ?? []), [statuses.data]);
  const active = providers.find((item) => item.id === provider)!;
  const submit = () => { if (apiKey.trim().length < 10 || save.isPending) return; save.mutate({ provider, apiKey: apiKey.trim() }); };
  const confirmDelete = (id: ProviderId) => Alert.alert("حذف المفتاح؟", "سيُحذف المفتاح المشفّر لهذا الموفّر فوراً ولا يمكن استعادته.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => remove.mutate({ provider: id }) }]);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-4" containerClassName="bg-background" safeAreaClassName="bg-background"><View style={styles.page}><ScreenHeading eyebrow="OPTIONAL BYOK" title="مفتاحك الشخصي" action={<Pressable accessibilityRole="button" onPress={() => router.back()} style={styles.close}><IconSymbol name="xmark" size={20} color="#2563EB" /></Pressable>} /><View style={styles.notice}><IconSymbol name="lock.fill" size={19} color="#2563EB" /><Text style={styles.noticeText}>هذه ميزة اختيارية للمستخدم المتقدم. لا يظهر المفتاح مجدداً بعد الحفظ؛ يُختبر ثم يُشفّر على الخادم. لا تضف مفتاحك إذا كنت لا ترغب في ذلك.</Text></View><Text style={styles.label}>اختر الموفّر</Text><View style={styles.providerList}>{providers.map((item) => <Pressable key={item.id} accessibilityRole="radio" accessibilityState={{ selected: provider === item.id }} onPress={() => setProvider(item.id)} style={({ pressed }) => [styles.providerCard, provider === item.id && styles.providerCardActive, pressed && styles.pressed]}><View style={styles.providerInfo}><Text style={styles.providerName}>{item.name}</Text><Text style={styles.providerNote}>{item.note}</Text></View>{saved.has(item.id) ? <StatusPill tone="success" label="محفوظ" /> : <View style={styles.radio}>{provider === item.id ? <View style={styles.radioDot} /> : null}</View>}</Pressable>)}</View><View style={styles.form}><Text style={styles.formTitle}>مفتاح {active.name}</Text><TextInput value={apiKey} onChangeText={setApiKey} placeholder="الصق مفتاح API هنا" placeholderTextColor="#8592B8" secureTextEntry autoCapitalize="none" autoCorrect={false} style={styles.input} accessibilityLabel="مفتاح API الشخصي" textAlign="left" /><Pressable accessibilityRole="button" disabled={apiKey.trim().length < 10 || save.isPending} onPress={submit} style={({ pressed }) => [styles.saveButton, (apiKey.trim().length < 10 || save.isPending) && styles.disabled, pressed && styles.pressed]}><Text style={styles.saveText}>{save.isPending ? "جارٍ الاختبار والحفظ…" : "اختبر المفتاح واحفظه"}</Text></Pressable>{save.error ? <Text style={styles.error}>{save.error.message}</Text> : null}</View><Text style={styles.deleteLabel}>المفاتيح المحفوظة</Text>{providers.filter((item) => saved.has(item.id)).length ? providers.filter((item) => saved.has(item.id)).map((item) => <Pressable key={`delete-${item.id}`} accessibilityRole="button" onPress={() => confirmDelete(item.id)} style={({ pressed }) => [styles.deleteRow, pressed && styles.pressed]}><IconSymbol name="trash.fill" size={17} color="#B2273E" /><Text style={styles.deleteText}>حذف مفتاح {item.name}</Text></Pressable>) : <Text style={styles.empty}>لم تحفظ أي مفتاح شخصي بعد.</Text>}<Text style={styles.help}>للحصول على مفتاح مجاني، أنشئ حساباً لدى الموفّر الذي اخترته، ثم أنشئ API Key من صفحة المفاتيح الخاصة به والصقه هنا. إن لم تكن متأكداً، اترك هذه الصفحة واستخدم الحصة المجانية للتطبيق.</Text></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 10, gap: 12 }, close: { width: 38, height: 38, borderRadius: 19, justifyContent: "center", alignItems: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E5EA" }, notice: { flexDirection: "row-reverse", gap: 9, backgroundColor: "#EEF4FF", borderColor: "#D7E6FF", borderWidth: 1, padding: 13, borderRadius: 15 }, noticeText: { color: "#4E5C78", fontSize: 12, lineHeight: 19, textAlign: "right", flex: 1 }, label: { color: "#4B4B55", fontSize: 12, fontWeight: "900", textAlign: "right", marginTop: 4 }, providerList: { gap: 8 }, providerCard: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E5EA", borderRadius: 14, padding: 12 }, providerCardActive: { backgroundColor: "#F4F8FF", borderColor: "#9CC0FF" }, providerInfo: { alignItems: "flex-end", gap: 3, flex: 1 }, providerName: { color: "#29292F", fontSize: 14, fontWeight: "900" }, providerNote: { color: "#7E7E87", fontSize: 11 }, radio: { width: 19, height: 19, borderRadius: 10, borderWidth: 2, borderColor: "#98A0AF", justifyContent: "center", alignItems: "center" }, radioDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: "#2563EB" }, form: { backgroundColor: "#FFFFFF", borderColor: "#E5E5EA", borderWidth: 1, borderRadius: 16, padding: 13, gap: 9 }, formTitle: { color: "#29292F", fontSize: 13, fontWeight: "900", textAlign: "right" }, input: { minHeight: 45, backgroundColor: "#FAFAFC", borderWidth: 1, borderColor: "#E0E0E5", borderRadius: 10, color: "#29292F", paddingHorizontal: 11, fontSize: 13 }, saveButton: { minHeight: 44, borderRadius: 10, backgroundColor: "#2563EB", alignItems: "center", justifyContent: "center" }, saveText: { color: "#FFFFFF", fontWeight: "900", fontSize: 13 }, error: { color: "#C7374F", fontSize: 11, lineHeight: 17, textAlign: "right" }, deleteLabel: { color: "#4B4B55", fontSize: 12, fontWeight: "900", textAlign: "right" }, deleteRow: { flexDirection: "row-reverse", justifyContent: "center", gap: 8, paddingVertical: 12, backgroundColor: "#FFF4F5", borderWidth: 1, borderColor: "#F1D0D6", borderRadius: 12 }, deleteText: { color: "#B2273E", fontSize: 12, fontWeight: "900" }, empty: { color: "#7C7C85", fontSize: 12, textAlign: "right" }, help: { color: "#777780", fontSize: 11, lineHeight: 18, textAlign: "right", paddingVertical: 6 }, disabled: { opacity: 0.48 }, pressed: { opacity: 0.76, transform: [{ scale: 0.98 }] } });
