import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";

type Plugin = { id: string; name: string; detail: string; icon: "books.vertical.fill" | "code" | "pencil" | "sparkles" | "gavel"; tone: string; connection: "غير متصل" | "يتطلب تفويضاً" };
const plugins: Plugin[] = [
  { id: "drive", name: "Google Drive", detail: "البحث في ملفاتك ومراجعة المستندات بعد التفويض.", icon: "books.vertical.fill", tone: "#2E8B57", connection: "يتطلب تفويضاً" },
  { id: "github", name: "GitHub", detail: "مراجعة المستودعات والقضايا وطلبات السحب بعد التفويض.", icon: "code", tone: "#24292F", connection: "يتطلب تفويضاً" },
  { id: "notion", name: "Notion", detail: "استخدام صفحاتك وقواعد المعرفة المتصلة بعد التفويض.", icon: "pencil", tone: "#111111", connection: "غير متصل" },
  { id: "slack", name: "Slack", detail: "تلخيص القنوات أو البحث في الرسائل بعد التفويض.", icon: "sparkles", tone: "#7D3B81", connection: "يتطلب تفويضاً" },
  { id: "calendar", name: "Google Calendar", detail: "عرض أو اقتراح تنظيم المواعيد بعد التفويض.", icon: "gavel", tone: "#3575DB", connection: "يتطلب تفويضاً" },
];

export default function PluginsScreen() {
  const router = useRouter();
  const renderPlugin = ({ item }: { item: Plugin }) => <View style={styles.card}><View style={[styles.icon, { backgroundColor: item.tone }]}><IconSymbol name={item.icon} size={24} color="#FFFFFF" /></View><View style={styles.copy}><Text style={styles.name}>{item.name}</Text><Text style={styles.detail}>{item.detail}</Text></View><Pressable accessibilityRole="button" onPress={() => Alert.alert("يتطلب تفويضاً", `ربط ${item.name} يحتاج تفويض حسابك لهذه المنصة. سيظهر زر الربط بعد إضافة خدمة التكامل الخاصة بك.`)} style={styles.connect}><Text style={styles.connectText}>ربط</Text></Pressable></View>;
  return <ScreenContainer className="px-5" containerClassName="bg-background" safeAreaClassName="bg-background"><View style={styles.page}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="رجوع" onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.right" size={24} color="#19191C" /></Pressable><Text style={styles.title}>المكونات الإضافية</Text><View style={styles.placeholder} /></View><Text style={styles.intro}>اربط المنصات التي تملكها لتستخدمها داخل المحادثة. لا يصل Rebel AI إلى أي حساب قبل موافقتك وتفويضك الصريح.</Text><View style={styles.featured}><Text style={styles.featuredLabel}>مكتبة المنصات</Text><Text style={styles.featuredValue}>ابدأ بمنصة واحدة</Text></View><FlatList data={plugins} renderItem={renderPlugin} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 8 }, header: { height: 52, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginBottom: 15 }, back: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, title: { fontSize: 24, fontWeight: "800", color: "#17171A" }, placeholder: { width: 44 }, intro: { color: "#6F6F78", fontSize: 14, lineHeight: 22, textAlign: "right", marginBottom: 16 }, featured: { backgroundColor: "#EEF4FF", borderWidth: 1, borderColor: "#D9E6FF", padding: 14, borderRadius: 16, flexDirection: "row-reverse", justifyContent: "space-between", marginBottom: 16 }, featuredLabel: { color: "#2563EB", fontSize: 13, fontWeight: "800" }, featuredValue: { color: "#53647F", fontSize: 12 }, list: { gap: 10, paddingBottom: 26 }, card: { flexDirection: "row-reverse", alignItems: "center", gap: 12, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E8E8EB", padding: 13, borderRadius: 17 }, icon: { width: 48, height: 48, borderRadius: 15, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, gap: 4 }, name: { color: "#25252A", fontSize: 16, fontWeight: "800", textAlign: "right" }, detail: { color: "#74747D", fontSize: 11, lineHeight: 17, textAlign: "right" }, connect: { backgroundColor: "#F1F1F3", paddingHorizontal: 12, paddingVertical: 9, borderRadius: 12 }, connectText: { color: "#323238", fontSize: 12, fontWeight: "800" } });
