import { Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenHeading, StatusPill } from "@/components/rebel-ui";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useRebelSession } from "@/lib/rebel-session";

export default function AccountScreen() {
  const router = useRouter();
  const { session, endSession } = useRebelSession();
  const account = session?.account;
  const signOut = async () => { haptic.medium(); await endSession(); router.replace("/login" as never); };
  const isOwner = account?.role === "owner";
  return <ScreenContainer className="px-4" containerClassName="bg-background" safeAreaClassName="bg-background"><View style={styles.page}><ScreenHeading eyebrow="REBEL AI ACCOUNT" title="حسابي" action={<StatusPill tone="success" label="متصل" />} /><View style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>{account?.displayName.slice(0, 1).toUpperCase() ?? "R"}</Text></View><Text style={styles.name}>{account?.displayName ?? "حساب Rebel AI"}</Text><Text style={styles.caption}>@{account?.username}</Text><View style={styles.infoRow}><Text style={styles.infoValue}>{isOwner ? "مالك التطبيق" : "مستخدم Rebel AI"}</Text><Text style={styles.infoLabel}>نوع الحساب</Text></View></View><View style={styles.notice}><IconSymbol name="checkmark.seal.fill" size={20} color="#2563EB" /><Text style={styles.noticeText}>يُحفظ سجل هذه الجلسة وذاكرتها بشكل منفصل عن أي حساب آخر على هذا الجهاز.</Text></View><Pressable accessibilityRole="button" onPress={() => router.push("/settings" as never)} style={({ pressed }) => [styles.settings, pressed && styles.pressed]}><IconSymbol name="gearshape.fill" size={20} color="#2563EB" /><Text style={styles.settingsText}>الإعدادات والحصة والمفاتيح الشخصية</Text></Pressable><Pressable accessibilityRole="button" onPress={signOut} style={({ pressed }) => [styles.logout, pressed && styles.pressed]}><IconSymbol name="xmark" size={18} color="#B2273E" /><Text style={styles.logoutText}>تسجيل الخروج</Text></Pressable></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 10, gap: 16 }, profileCard: { alignItems: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E5EA", borderRadius: 20, padding: 24, gap: 7 }, avatar: { width: 76, height: 76, borderRadius: 38, backgroundColor: "#EAF1FF", justifyContent: "center", alignItems: "center", marginBottom: 4 }, avatarText: { color: "#2563EB", fontSize: 30, fontWeight: "900" }, name: { color: "#25252B", fontSize: 20, fontWeight: "900", textAlign: "center" }, caption: { color: "#75757E", fontSize: 13, textAlign: "center" }, infoRow: { flexDirection: "row-reverse", justifyContent: "space-between", width: "100%", borderTopColor: "#ECECEF", borderTopWidth: 1, marginTop: 10, paddingTop: 13 }, infoLabel: { color: "#85858E", fontSize: 12 }, infoValue: { color: "#4B4B54", fontSize: 12, fontWeight: "700" }, notice: { flexDirection: "row-reverse", alignItems: "flex-start", gap: 10, backgroundColor: "#EEF4FF", borderWidth: 1, borderColor: "#D7E6FF", borderRadius: 16, padding: 14 }, noticeText: { flex: 1, color: "#4F5D79", fontSize: 12, lineHeight: 19, textAlign: "right" }, settings: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 9, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D7E6FF", paddingVertical: 13, borderRadius: 14 }, settingsText: { color: "#2563EB", fontSize: 14, fontWeight: "900" }, logout: { flexDirection: "row-reverse", justifyContent: "center", alignItems: "center", gap: 8, paddingVertical: 13, borderRadius: 14, backgroundColor: "#FFF4F5", borderWidth: 1, borderColor: "#F1CDD3" }, logoutText: { color: "#B2273E", fontSize: 14, fontWeight: "900" }, pressed: { opacity: 0.76, transform: [{ scale: 0.98 }] } });
