import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { IconButton, ScreenHeading, SectionTitle, StatusPill } from "@/components/rebel-ui";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { haptic } from "@/lib/haptics";
import { useRebelStore, type MemoryItem } from "@/lib/rebel-store";

export default function MemoryScreen() {
  const { memories, addMemory, removeMemory } = useRebelStore();
  const [query, setQuery] = useState("");
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const filtered = useMemo(() => memories.filter((memory) => `${memory.title} ${memory.content} ${memory.category}`.toLowerCase().includes(query.trim().toLowerCase())), [memories, query]);
  const add = () => { if (!title.trim() || !content.trim()) return; addMemory({ title: title.trim(), content: content.trim(), category: "سياق", source: "إضافة يدوية" }); setTitle(""); setContent(""); haptic.success(); };
  const renderMemory = ({ item }: { item: MemoryItem }) => <View style={styles.memoryCard}><View style={styles.cardTop}><IconButton icon="trash.fill" label={`حذف ${item.title}`} onPress={() => { removeMemory(item.id); haptic.medium(); }} /><StatusPill tone="primary" label={item.category} /></View><Text style={styles.memoryTitle}>{item.title}</Text><Text style={styles.memoryContent}>{item.content}</Text><Text style={styles.memoryMeta}>{item.source} · {new Date(item.createdAt).toLocaleDateString("ar-EG")}</Text></View>;
  return <ScreenContainer className="px-4" containerClassName="bg-background" safeAreaClassName="bg-background"><View style={styles.page}><ScreenHeading eyebrow="PRIVATE CONTEXT" title="الذاكرة" action={<StatusPill tone="neutral" label={`${memories.length} عنصر`} />} /><Text style={styles.intro}>مساحة شخصية لما تريد أن يحتفظ به Rebel AI. تظل البيانات على جهازك ويمكنك إدارتها في أي وقت.</Text><View style={styles.searchBox}><IconSymbol name="magnifyingglass" size={19} color="#777780" /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث في الذاكرة" placeholderTextColor="#94949C" style={styles.searchInput} accessibilityLabel="بحث في الذاكرة" /></View><SectionTitle title="إضافة معلومة" detail="حفظ محلي" /><View style={styles.addBox}><TextInput value={title} onChangeText={setTitle} placeholder="عنوان قصير" placeholderTextColor="#92929B" style={styles.titleInput} accessibilityLabel="عنوان المعلومة" /><TextInput value={content} onChangeText={setContent} placeholder="ما الذي تريد أن يتذكره Rebel AI؟" placeholderTextColor="#92929B" style={styles.contentInput} multiline accessibilityLabel="محتوى المعلومة" /><Pressable accessibilityRole="button" onPress={add} disabled={!title.trim() || !content.trim()} style={({ pressed }) => [styles.addButton, (!title.trim() || !content.trim()) && styles.disabled, pressed && styles.pressed]}><Text style={styles.addButtonText}>حفظ في الذاكرة</Text></Pressable></View><SectionTitle title="العناصر المحفوظة" detail={`${filtered.length} نتيجة`} /><FlatList data={filtered} renderItem={renderMemory} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>ذاكرتك فارغة حتى الآن</Text><Text style={styles.emptyText}>أضف معلومة بنفسك أو وافق على اقتراح في شاشة الموافقات.</Text></View>} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 10 }, intro: { color: "#6E6E77", fontSize: 14, lineHeight: 22, textAlign: "right", marginBottom: 15 }, searchBox: { flexDirection: "row-reverse", alignItems: "center", gap: 8, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E5EA", padding: 10, borderRadius: 15, marginBottom: 20 }, searchInput: { flex: 1, color: "#25252B", fontSize: 14, textAlign: "right", minHeight: 30 }, addBox: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E5EA", padding: 14, borderRadius: 17, gap: 10, marginBottom: 20 }, titleInput: { color: "#25252B", fontSize: 14, textAlign: "right", borderBottomWidth: 1, borderBottomColor: "#ECECEF", paddingVertical: 8 }, contentInput: { color: "#25252B", fontSize: 14, textAlign: "right", minHeight: 56, lineHeight: 21 }, addButton: { backgroundColor: "#2563EB", paddingVertical: 12, alignItems: "center", borderRadius: 12 }, addButtonText: { color: "#FFFFFF", fontWeight: "800", fontSize: 13 }, disabled: { opacity: 0.45 }, pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] }, list: { gap: 10, paddingBottom: 24 }, memoryCard: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 15, borderWidth: 1, borderColor: "#E7E7EA", gap: 8 }, cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, memoryTitle: { color: "#28282E", fontSize: 16, fontWeight: "800", textAlign: "right" }, memoryContent: { color: "#5C5C65", fontSize: 13, lineHeight: 20, textAlign: "right" }, memoryMeta: { color: "#92929A", fontSize: 10, textAlign: "right" }, empty: { alignItems: "center", padding: 30, backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E7E7EA" }, emptyTitle: { color: "#303037", fontWeight: "800", fontSize: 16 }, emptyText: { color: "#777780", fontSize: 13, textAlign: "center", lineHeight: 20, marginTop: 7 } });
