import { FlatList, StyleSheet, Text, View } from "react-native";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenHeading, SectionTitle, StatusPill } from "@/components/rebel-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useRebelStore, type SourceItem } from "@/lib/rebel-store";

export default function SourcesScreen() {
  const { sources } = useRebelStore();
  const verified = sources.filter((source) => source.status === "موثوق").length;
  const renderSource = ({ item }: { item: SourceItem }) => {
    const tone = item.status === "موثوق" ? "success" : item.status === "قيد المراجعة" ? "warning" : "neutral";
    return <View style={styles.card}><View style={styles.top}><StatusPill label={item.status} tone={tone} /><View style={styles.score}><Text style={styles.scoreValue}>{item.score}</Text><Text style={styles.scoreUnit}>/100</Text></View></View><Text style={styles.title}>{item.title}</Text><Text style={styles.domain}>{item.domain}</Text><View style={styles.note}><IconSymbol name="sparkles" color="#44D7FF" size={16} /><Text style={styles.noteText}>{item.note}</Text></View></View>;
  };
  return <ScreenContainer className="px-4" containerClassName="bg-background" safeAreaClassName="bg-background"><View style={styles.page}><ScreenHeading eyebrow="EVIDENCE BEFORE ACTION" title="المصادر" action={<StatusPill tone="success" label={`${verified} موثوق`} />} /><Text style={styles.intro}>يعرض Rebel AI مستوى الثقة وسياق كل معلومة. المصدر الجيد يدعم التحليل، لكنه لا يحوّل الاستنتاج إلى يقين تلقائي.</Text><View style={styles.rule}><Text style={styles.ruleTitle}>قاعدة Rebel AI</Text><Text style={styles.ruleText}>لا تُنقل أي معرفة مقترحة إلى الذاكرة قبل أن تراجعها وتوافق عليها.</Text></View><SectionTitle title="سجل التحقق" detail="مراجعة شفافة" /><FlatList data={sources} renderItem={renderSource} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 10 }, intro: { color: "#AEB7D6", fontSize: 14, lineHeight: 22, textAlign: "right", marginBottom: 15 }, rule: { backgroundColor: "#1A2645", borderColor: "#3A4E7D", borderWidth: 1, borderRadius: 16, padding: 14, gap: 5, marginBottom: 20 }, ruleTitle: { color: "#77E2FF", fontSize: 13, fontWeight: "900", textAlign: "right" }, ruleText: { color: "#D4DCF4", fontSize: 13, lineHeight: 20, textAlign: "right" }, list: { gap: 11, paddingBottom: 24 }, card: { padding: 15, gap: 8, borderRadius: 17, borderWidth: 1, borderColor: "#2B3B62", backgroundColor: "#121A31" }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, score: { flexDirection: "row", alignItems: "baseline", gap: 2 }, scoreValue: { color: "#57E4AC", fontWeight: "900", fontSize: 22 }, scoreUnit: { color: "#9BA7CC", fontWeight: "700", fontSize: 10 }, title: { color: "#F5F7FF", fontSize: 17, fontWeight: "800", textAlign: "right" }, domain: { color: "#8491B7", fontSize: 12, textAlign: "right" }, note: { flexDirection: "row-reverse", gap: 7, alignItems: "flex-start", backgroundColor: "#192541", borderRadius: 10, padding: 9 }, noteText: { color: "#B8C3E4", fontSize: 12, lineHeight: 18, textAlign: "right", flex: 1 } });
