import { FlatList, StyleSheet, Text, View } from "react-native";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenHeading, SectionTitle, StatusPill } from "@/components/rebel-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useRebelStore, type SourceItem } from "@/lib/rebel-store";

export default function SourcesScreen() {
  const { sources } = useRebelStore();
  const verified = sources.filter((source) => source.status === "موثوق").length;
  const renderSource = ({ item }: { item: SourceItem }) => { const tone = item.status === "موثوق" ? "success" : item.status === "قيد المراجعة" ? "warning" : "neutral"; return <View style={styles.card}><View style={styles.top}><StatusPill label={item.status} tone={tone} /><Text style={styles.score}>{item.score}<Text style={styles.scoreUnit}>/100</Text></Text></View><Text style={styles.title}>{item.title}</Text><Text style={styles.domain}>{item.domain}</Text><View style={styles.note}><IconSymbol name="sparkles" color="#2563EB" size={16} /><Text style={styles.noteText}>{item.note}</Text></View></View>; };
  return <ScreenContainer className="px-4" containerClassName="bg-background" safeAreaClassName="bg-background"><View style={styles.page}><ScreenHeading eyebrow="EVIDENCE, NOT ASSUMPTION" title="المصادر" action={<StatusPill tone="success" label={`${verified} موثوق`} />} /><Text style={styles.intro}>يعرض Rebel AI مستوى الثقة وسياق كل معلومة. المصدر الجيد يساعد على الفهم ولا يحوّل الاحتمال إلى حقيقة تلقائياً.</Text><View style={styles.rule}><Text style={styles.ruleTitle}>مبدأ العمل</Text><Text style={styles.ruleText}>تظل المعرفة المقترحة بانتظار قرارك قبل أن تحفظ في الذاكرة.</Text></View><SectionTitle title="سجل التحقق" detail="مراجعة شفافة" /><FlatList data={sources} renderItem={renderSource} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 10 }, intro: { color: "#6E6E77", fontSize: 14, lineHeight: 22, textAlign: "right", marginBottom: 15 }, rule: { backgroundColor: "#EEF4FF", borderColor: "#D7E6FF", borderWidth: 1, borderRadius: 16, padding: 14, gap: 5, marginBottom: 20 }, ruleTitle: { color: "#2563EB", fontSize: 13, fontWeight: "800", textAlign: "right" }, ruleText: { color: "#4A5873", fontSize: 13, lineHeight: 20, textAlign: "right" }, list: { gap: 11, paddingBottom: 24 }, card: { padding: 15, gap: 8, borderRadius: 17, borderWidth: 1, borderColor: "#E7E7EA", backgroundColor: "#FFFFFF" }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, score: { color: "#16835D", fontWeight: "900", fontSize: 22 }, scoreUnit: { color: "#8B8B94", fontSize: 10 }, title: { color: "#2B2B31", fontSize: 17, fontWeight: "800", textAlign: "right" }, domain: { color: "#81818A", fontSize: 12, textAlign: "right" }, note: { flexDirection: "row-reverse", gap: 7, alignItems: "flex-start", backgroundColor: "#F5F8FF", borderRadius: 10, padding: 10 }, noteText: { color: "#596170", fontSize: 12, lineHeight: 18, textAlign: "right", flex: 1 } });
